version: '3'

services:
  vending_web:
    build: .
  vending_nginx:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - URL=api.snackhack.tech
      - SUBDOMAINS=,
      - VALIDATION=http
      - DNSPLUGIN=cloudflare #optional
      # - DUCKDNSTOKEN=token #optional
      - EMAIL=jam93t@mst.edu #optional
      - DHLEVEL=2048 #optional
      - ONLY_SUBDOMAINS=false #optional
      # - EXTRA_DOMAINS=extradomains #optional
      - STAGING=false #optional
    volumes:
      - ./.docker/letsencrypt:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
