version: '3'

services:
  vending_db:
    image: "postgres:11"
    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      - db_nw
    environment:
      - POSTGRES_USER=vending
      - POSTGRES_PASSWORD=vending
  vending_web:
    restart: unless-stopped
    networks:
      - db_nw
      - web_nw
    depends_on:
      - vending_db
    env_file:
      - ./.docker/web.env
    environment:
      - DB_HOST=vending_db
      - DB_USERNAME=vending
      - DB_PASSWORD=vending
  vending_nginx:
    image: "nginx"
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./.docker/conf.d:/etc/nginx/conf.d
    networks:
      - web_nw
    depends_on:
      - vending_web
networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge
